<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-FEJVQKG" name="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase1" tests="4" failures="1" timestamp="2021-10-20T15:28:09 IST" time="28.395" errors="0">
  <testcase name="name" time="9.082" classname="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase1">
    <skipped/>
  </testcase> <!-- name -->
  <system-out/>
  <testcase name="name" time="6.309" classname="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase1">
    <skipped/>
  </testcase> <!-- name -->
  <system-out/>
  <testcase name="name" time="6.488" classname="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase1">
    <skipped/>
  </testcase> <!-- name -->
  <system-out/>
  <testcase name="name" time="6.516" classname="com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase1">
    <failure type="java.lang.AssertionError" message="expected [s] but found [p]">
      <![CDATA[java.lang.AssertionError: expected [s] but found [p]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase1.name(DemoTestcase1.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- name -->
  <system-out/>
</testsuite> <!-- com.perfaware.automation.oms.sterling.common.testcases.DemoTestcase1 -->
